import PostMenu2 from "@/app/(blogpost)/Blog2/PostMenu2";
import BlogMenu from "@/components/Blog/BlogMenu";
import CommentBox from "@/components/DetailProduct/CommentBox";
import TitlePage from "@/components/TitlePage/page";
import Image from "next/image";
import Link from "next/link";

function Blog2() {
    return (
        <div>
            <TitlePage detailBlog pageCurrent="Blog 2" />
            <div className="container">
                <div className="row w-[95%] xs:w-[90%] mx-auto py-10 flex flex-col-reverse lg:flex-row gap-5">
                    <BlogMenu detailBlogMenu />
                    <div className="basis-3/4">
                        <div className="font-medium text-xl tracking-wide">Bài viết mẫu 2</div>
                        <div className="text-xs mt-2 tracking-wide">Nhiều ba mẹ rất băn khoăn vì con càng lớn càng nhút nhát, không biết làm thế nào giúp con dạn dĩ hơn. Vì sao trẻ nhút nhát? Sau đây, hãy cùng với phucngocan.com tìm hiểu về những bí quyết giúp trẻ vượt qua sự nhút nhát và các ba mẹ cùng đồng hành với con trong bài viết dưới đây nhé! </div>
                        <PostMenu2 />
                        <h3 className="mt-4 text-xl font-semibold">Vì sao con ngày càng nhát?</h3>
                        <div className="mt-2 text-xs tracking-wide">Trước tiên, bạn nên biết việc trẻ con nhút nhát không có gì là bất thường. Không hẳn vì ba mẹ nuôi dạy con sai cách. Đây là tính cách xuất hiện hầu hết ở trẻ nhỏ từ 6 tháng đến 3 tuổi. Vì thế giới xung quanh còn quá mới mẻ và lạ lẫm với chúng. Các bé sẽ có xu hướng gần gũi với những người thân quen nhất. Trẻ cảm thấy gượng gạo và căng thẳng mỗi khi trở thành trung tâm của sự chú ý. Kể cả khi đó là sự chú ý tích cực… Đó là lý do con nhút nhát.</div>
                        <div className="mt-2 text-xs tracking-wide">Và theo lẽ tự nhiên, khi trẻ được hơn 3 hoặc 4 tuổi sẽ bắt đầu có nhu cầu vui chơi và tương tác với bạn bè đồng trang lứa. Nhưng nếu lúc này tính nhút nhát vẫn tiếp tục kéo dài, thì chúng ta cần có phương pháp tích cực để thay đổi trẻ.</div>
                        <Image src={'/blog-2-1.png'} alt="" width={600} height={100} className="mx-auto mt-4" />
                        <figcaption className="text-center text-xs mt-2 italic">Trẻ nhút nhát thường sẽ có biểu hiện rõ ràng mà phụ huynh đều có thể thấy được</figcaption>
                        <div className="mt-2 text-xs tracking-wide">Nhiều bé học hành rất thông minh. Khi ở nhà cùng ba mẹ thì nói năng trôi chảy và tiếp thu rất nhanh. Thậm chí còn hay vặn vẹo bố mẹ. Nhựng khi ra ngoài, hoặc có khách tới chơi nhà thì trở nên rụt rè, hay sợ. Không hòa nhập cùng người khác được.</div>
                        <div className="mt-2 text-xs tracking-wide">Có những trẻ lúc nhỏ thì vẫn mạnh dạn, tự nhiên, nhưng càng lớn càng thay đổi. Nhút nhát và thụ động. Điều gì khiến con trở nên như vậy? Theo TS Vũ Thu Hương, cách dạy sai của ba mẹ sai sẽ khiến trẻ nhút nhát. Dần trở nên thiếu tự tin. Một trong những sai lầm ba mẹ thường gặp là:</div>
                        <h4 className="mt-2 font-semibold text-lg">Ba mẹ hay căng thẳng</h4>
                        <div className="mt-2 text-xs tracking-wide">Nếu như cha mẹ thường stress hay căng thẳng thì dần sẽ gây ảnh hưởng, khiến cho bé có một nỗi sợ hãi mơ hồ. Thường khi cha mẹ lo lắng thì con sẽ bị truyền lo lắng đó vào người và cháu sẽ cảm thấy sợ.</div>
                        <Image src={'/blog-2-2.png'} alt="" width={600} height={100} className="mx-auto mt-4" />
                        <figcaption className="text-center text-xs mt-2 italic">Sự lo lắng của ba mẹ về sự nhút nhát của con cái có thể khiến trẻ cảm thấy thiếu tự tin hơn</figcaption>
                        <div className="mt-2 text-xs tracking-wide">Khi thấy bé hay sợ hãi, ba mẹ lại càng lo lắng cho con. Nỗi lo lắng này hoàn toàn có thể khiến trẻ cảm nhận được và càng thêm sợ hãi.</div>
                        <h4 className="mt-2 font-semibold text-lg">Chăm bẵm con quá mức sẽ khiến trẻ nhút nhát</h4>
                        <div className="mt-2 text-xs tracking-wide">Cha mẹ chăm bẵm con quá cũng sẽ khiến con bị thiếu tự tin. Việc gì bé làm cũng khiến ba mẹ cảm thấy lo lắng và luôn muốn giúp đỡ. Mỗi lần vấp ngã ba mẹ chạy lại bế lên dỗ dành. Ba mẹ chăm sóc hoàn toàn từ A – Z… Do nhận được quá nhiều sự bao bọc trong gia đình, trẻ chưa tự chủ động làm một cái gì mà không có sự theo dõi và chỉ bảo của người lớn. Điều này khiến trẻ không tự tin một chút nào nếu không có người lớn ở bên chỉ bảo.</div>
                        <h4 className="mt-2 font-semibold text-lg">Tập trung vào những điểm tiêu cực, chê bai con</h4>
                        <div className="mt-2 text-xs tracking-wide">Cũng có trường hợp trẻ muốn chủ động làm một điều gì đó. Nhưng thay vì tập trung vào những điểm tích cực đã làm được, thì bé lại nhận được những lời bình luận không hài lòng.</div>
                        <Image src={'/blog-2-3.png'} alt="" width={600} height={100} className="mx-auto mt-4" />
                        <figcaption className="text-xs text-center italic mt-2">Những lời trách móc chê bai của phụ huynh là nguyên nhân khiên scho trẻ ngày càng tự ti vào bản thân</figcaption>
                        <div className="mt-2 text-xs tracking-wide">Ví dụ như muốn tự rót nước mời mẹ nhưng cháu chưa đủ khéo để rót nước vào cốc mà không đổ ra ngoài. Nếu cha mẹ tâm lý thì sẽ khen con là <span className="italic">“Con tôi đã lớn rồi, con đã biết rót nước mời mẹ rồi. Lần sau con đỡ tay phía dưới bình nước thì sẽ rót được khéo hơn không bị tràn ra ngoài con nhé”.</span> Nhưng có thể nhiều cha mẹ ngăn cản ngay bằng những câu như <span>“Thôi để đấy! Lại đổ tràn ra ngoài rồi thấy chưa!…”.</span> Những lời nói không hài lòng như vậy một mặt làm trẻ không biết phải làm thế nào cho đúng. Mặt khác làm cho trẻ học được cách để tránh bị phê bình là không làm gì cả, không tham gia gì cả.</div>
                        <h3 className="mt-4 text-xl font-semibold">Những hậu quả mà trẻ nhút nhát có thể gặp phải </h3>
                        <ul className="text-xs leading-7 list-disc list-inside tracking-wide mt-2">
                            <li>Giảm cơ hội phát triển bản thân và kỹ năng sống cho trẻ</li>
                            <li>Ít bạn bè hơn</li>
                            <li>Cảm thấy ít vui vẻ khi tham gia các hoạt động cần tương tác với người khác như thể thao, âm nhạc, khiêu vũ,…</li>
                            <li>Tăng cảm giác cô đơn, cảm thấy bản thân không quan trọng, giảm lòng tự trọng</li>
                            <li>Giảm khả năng đạt được mục tiêu vì sợ bị người khác đánh giá.</li>
                            <li>Hay lo lắng, sợ sệt.</li>
                            <li>Có những biểu hiện như đỏ mặt, toát mồ hôi, đỏ mặt, lắp bắp.</li>
                        </ul>
                        <h3 className="mt-4 text-xl font-semibold">Làm gì để giúp trẻ nhút nhát tự tin hơn?</h3>
                        <div className="mt-2 text-xs tracking-wide">Để giúp trẻ, ba mẹ cần xem xét lại việc chăm sóc và nuôi dạy con của mình. Không đem sự căng thẳng trong cơ quan, nơi làm việc hay gia đình vào trong những lần giao tiếp với trẻ. Tránh mỉa mai, chỉ trích những việc trẻ làm chưa tốt. Hay so sánh trẻ với những những anh chị, bạn bè cùng chơi. Ngoài ra, ba mẹ cũng hãy tham khảo những cách thức dưới đây:</div>
                        <h4 className="mt-2 font-semibold text-lg">Chỉ cho con cách tự chăm sóc bản thân</h4>
                        <div className="mt-2 text-xs tracking-wide">Thông thường, những trẻ chỉ hoạt ngôn lanh lợi ở nhà, còn khi ra ngoài thì trẻ nhút nhát, rụt rè. Là do cháu cảm thấy không an toàn và tự tin khi phải quyết định hoặc hành động một mình. Vì vậy, ba mẹ phải cho con tập làm mọi việc chăm sóc cho chính bản thân. Phát triển cho trẻ tinh thần tự lập. Thậm chí, bạn có thể nhờ cháu cả một số công việc nhà đơn giản. Khi cháu làm tốt, cần khen ngợi và khích lệ con thật nhiều.</div>
                        <Image src={'/blog-2-4.png'} alt="" width={600} height={100} className="mx-auto mt-4" />
                        <figcaption className="text-xs italic text-center mt-2">Trẻ có tính tự lập sẽ trở nên dạn dĩ và lanh lợi hơn</figcaption>
                        <h4 className="mt-2 font-semibold text-lg">Không ép trẻ phải giao tiếp khi con không thoải mái</h4>
                        <div className="mt-2 text-xs tracking-wide">Khi con ra ngoài chơi hoặc có người lạ đến nhà, bạn đừng ép con phải chào hỏi hay nói chuyện vui vẻ. Hãy để con tự nhiên. Khi con quan sát kĩ mà thấy khách không có biểu hiện hại bé thì bé sẽ tự nhiên lại gần và tiếp xúc thôi. Đó là cách dạy con ngoan hiệu quả. Việc thúc ép khiến bé càng thêm lo lắng và sợ hãi.</div>
                        <div className="mt-2 text-xs tracking-wide">Xem thêm: <Link href={'https://hipencilstore.com/blogs/choi-cung-be/tim-hieu-ve-do-choi-montessori-top-do-choi-montessori-tot-nhat-cho-be'}>Tìm Hiểu Về Đồ Chơi Montessori. Top Đồ Chơi Montessori Tốt Nhất Cho Bé</Link></div>
                        <h4 className="mt-2 font-semibold text-lg">Chủ động gần gũi, giúp trẻ chia sẻ và cởi mở</h4>
                        <div className="mt-2 text-xs tracking-wide">Cha mẹ phải chủ động gần gũi con và giúp trẻ cởi mở chia sẻ những khó khăn bằng lời. Cha mẹ nên tìm hiểu sâu hơn những cảm xúc hoặc suy nghĩ thực đằng sau lời nói. Ví dụ cha mẹ hỏi thêm vì sao con sợ người khác nhìn, tại sao con lại cảm thấy xấu hổ. Có thể các em có niềm tin là <span>“con chẳng thể nào làm một cái gì đúng cả”.</span> Hoặc <span>“mọi người sẽ cười khi con làm điều gì đó sai nên con mới tránh và xấu hổ”.</span></div>
                        <Image src={'/blog-2-5.png'} alt="" width={600} height={100} className="mx-auto mt-4" />
                        <figcaption className="mt-2 text-xs text-center italic">Ba mẹ trò chuyện nhiều với bé giúp bé giải quyết những khúc mắc trong lòng bé giúp bé tự tin hơn</figcaption>
                        <div className="mt-2 text-xs tracking-wide">Có thể giải thích cho con rằng sai sót là chuyện bình thường. Cha mẹ đôi lúc cũng sai nhưng không ai cười cha mẹ cả. Sau đó hỏi về những điểm mạnh của trẻ để các em cảm thấy tự tin hơn. Ví dụ như cha mẹ có thể nói là <span>“nhưng bố mẹ thấy ở nhà con kể chuyện rất hay. Nên bố mẹ tin rằng con có thể kể những câu chuyện đó cho các bạn“…</span> Đó là cách dạy trẻ tư duy kiểu Nhật, giúp trẻ tư duy tích cực. Bằng cách thức đó, cha mẹ sẽ giúp con có những niềm tin mới, tích cực hơn về bản thân. Từ đó con hủ động tích cực tham gia vào các hoạt động với bạn bè.</div>
                        <h4 className="mt-2 font-semibold text-lg">Khuyến khích trẻ tham gia hoạt động tập thể</h4>
                        <div className="mt-2 text-xs tracking-wide">Cha mẹ không nên bao bọc con quá mức. Hãy tạo những thách thức nhỏ để con tự thể hiện mình. Thường xuyên cho trẻ tiếp xúc, giao lưu với thế giới bên ngoài. Ví dụ như khuyến khích trẻ tham gia vào các hoạt động, trò chơi tập thể. Cho trẻ tham gia nhiều hơn các lớp ngoại khóa như học đàn, học vẽ, kỹ năng sống…</div>
                        <h4 className="mt-2 font-semibold text-lg">Hình thành cho bé “hình ảnh tích cực” của riêng mình</h4>
                        <div className="mt-2 text-xs tracking-wide">Nó có nghĩa là bản thân trẻ luôn cảm thấy tự tin. Chúng biết được những điểm mạnh, hạn chế của bản thân và tin tưởng vào khả năng của mình hơn. Những người tự tin thường thành công trong rất nhiều công việc vì họ có thể đương đầu với khó khăn và tự mình giải quyết chúng một cách tốt nhất.</div>
                        <Image src={'/blog-2-6.png'} alt="" width={600} height={100} className="mx-auto mt-4" />
                        <figcaption className="text-center text-xs italic mt-2">Hãy khích lệ và động viên tinh thần trẻ để trẻ có được sự tự tin trong những hoạt động thường nhật</figcaption>
                        <div className="mt-2 text-xs tracking-wide">Tương tự như vậy, để hình thành sự tự tin cho trẻ, cha mẹ hãy luôn tỏ ra tin tưởng vào con cái mình và luôn dành cho con những lời động viên tốt nhất, như: <span className="italic">“Cha mẹ tin rằng con sẽ làm được”</span> hay <span className="italic">“Cố gắng nhé, con sẽ làm được mà con yêu”</span> hoặc <span className="italic">“Đừng lo lắng, mẹ tin con còn có thể làm tốt hơn như vậy nữa”</span>… hãy dành những lời động viên tương tự trước khi trẻ thực hiện một công việc nào đó hoặc cần sự trợ giúp nhé, đây là một trong những phương pháp dạy con hay nhất chính là sự động viên. Những lời động viên ấy của cha mẹ như một thứ vũ khí tự nhiên sẽ khiến bé tự tin vào bản thân mình hơn rất nhiều và chắc con trẻ sẽ thể hiện năng lực hết mình để không phụ lòng cha mẹ quan sát.</div>
                        <h4 className="mt-2 font-semibold text-lg">Hãy dành lời khen đúng đắng và không nên la mắng</h4>
                        <div className="mt-2 text-xs tracking-wide">Khi trẻ làm đúng và hoàn thành tốt một công việc nào đó, cha mẹ hãy nên động viên và khen ngợi chúng nhưng hãy thật rõ ràng nhé, những cha mẹ đừng nên nói những câu đại loại như này: <span className="italic">“Con rất ngoan, con thật là giỏi”</span> mà thay vào đó hãy nên nói một cách rõ ràng là: <span className="italic">“Mẹ rất thích cách con dọn dẹp phòng của mình, con đã biết cách sắp xếp rồi đấy”.</span></div>
                        <div className="mt-2 text-xs tracking-wide">Nếu như con trẻ làm điều gì đó chưa đúng thì cha mẹ cần phải giải thích và chỉ ra những chỗ sai để giúp con biết vì sao mình sai và có thể sửa sai đúng cách nhé. Hãy đừng nên la mắng con, nếu tức giận cũng vẫn hay nên cho con biết vì sao chúng sai và nếu con vẫn sai con sẽ bị phạt. Làm như vậy sẽ khiến trẻ hiểu rằng nếu không có những sai lầm thì sẽ không thể tiến bộ lên được.</div>
                        <h4 className="mt-2 font-semibold text-lg">Trẻ sẽ học được nhiều hơn bằng việc tự mình cố gắng</h4>
                        <div className="mt-2 text-xs tracking-wide">Kiên trì và tự tin sẽ giúp trẻ làm và thành công rất nhiều việc. Vì thế, cha mẹ hãy cứ dành thời gian cho con để con có thể thử sức với những điều mới mẻ ngoài kia, chắc chắn chúng sẽ học được rất nhiều điều sau những lần thất bại đấy nhé. Cha mẹ chỉ có thể giúp đỡ trẻ khi thật sự cần thiết nhé.</div>
                        <Image src={'/blog-2-7.png'} alt="" width={600} height={100} className="mx-auto mt-4" />
                        <figcaption className="mt-2 text-center text-xs italic">Khi trẻ tự cố gắng thì sẽ học được sự bản lĩnh và tự tin vốn có</figcaption>
                        <div className="mt-2 text-xs tracking-wide">Như cách cha mẹ nước ngoài hay làm, khi con té phải để con tự đứng lên chứ không phải dựa lẫm và khóc thét như một người yếu đuối. Có như vậy con sẽ tự lập và cố gắng.</div>
                        <div className="mt-2 text-xs tracking-wide">Xem thêm các bài viết sau:</div>
                        <ul className="text-xs leading-7 list-disc list-inside tracking-wide mt-2">
                            <li><Link className="hover:text-mainGreen transition-all duration-150" href={'https://www.phucngocan.com/blogs/publish/tre-mat-tap-trung'}>Trẻ mất tập trung: Nguyên nhân, phương pháp dạy con hiệu quả</Link></li>
                            <li><Link className="hover:text-mainGreen transition-all duration-150" href={'https://www.phucngocan.com/blogs/publish/day-con-biet-ton-trong-loi-hua'}>Dạy con biết giá trị và tầm quan trọng của việc giữ lời hứa</Link></li>
                            <li><Link className="hover:text-mainGreen transition-all duration-150" href={'https://www.phucngocan.com/blogs/publish/luyen-con-tu-ngu'}>Tuyệt chiêu luyện con tự ngủ từ nhỏ hiệu quả mẹ cần biết</Link></li>
                        </ul>
                        <h4 className="mt-2 font-semibold text-lg">Cha mẹ phải là tấm gương cho con noi theo</h4>
                        <div className="mt-2 text-xs tracking-wide">Phần lớn trẻ con học tập từ những lời nói, hành động của cha mẹ, người lớn. Với trẻ thế giới rất mới lạ hoàn toàn và những gì chúng nghe được, thấy được là sẽ luôn bắt chước theo những hành vi của người lớn dù tốt hay xấu (bởi trẻ con chưa biết phân biệt đâu là đúng đâu là sai hay tốt xấu). Vậy nên nếu con trẻ thấy cha mẹ làm những hành động tiêu cực thì chúng sẽ làm theo và ngược lại con trẻ làm những điều tốt nếu cha mẹ làm điều tốt.</div>
                        <h4 className="mt-2 font-semibold text-lg">Bố mẹ luôn ở bên con</h4>
                        <div className="mt-2 text-xs tracking-wide">Hãy cho con bạn thấy bạn tin vào con và sẵn sàng ở bên con khi con gặp bất cứ vấn đề gì với xung quanh. Chẳng hạn như có ai đó nhận xét về con ngay trước mặt con như là &quot;bé có vẻ nhát nhỉ&quot;, &quot;con trai gì mà mắc cỡ như con gái vậy&quot;…, bố mẹ hãy thay con trả lời &quot;con không nhát đâu, lúc đầu con vậy chứ lát nữa là con tham gia liền à&quot;…</div>
                        <h4 className="mt-2 font-semibold text-lg">Đừng bao giờ so sánh</h4>
                        <div className="mt-2 text-xs tracking-wide">Đừng bao giờ so sánh con với bạn bè, hay anh chị em như &quot;nhìn kìa, bạn chơi một mình có sợ đâu?&quot;... Việc so sánh đó vô tình khiến con bị tổn thương, càng thu mình lại.</div>
                        <h4 className="mt-2 font-semibold text-lg">Giúp con thành thạo các kỹ năng mới</h4>
                        <div className="mt-2 text-xs tracking-wide">Có một điều đáng ngạc nhiên là: Những người hạnh phúc thường là những người đã thành thạo một kỹ năng. Giống như người lớn, một đứa trẻ hạnh phúc cần phải theo đuổi sở thích của riêng mình, nếu không sẽ không có niềm vui khi thành công. Ví dụ, khi con tập bắt bóng, bé sẽ học được từ những sai lầm của mình, phát triển tính kiên trì và kỷ luật. Sau đó con sẽ trải nghiệm được niềm vui thành công từ nỗ lực của chính mình.</div>
                        <Image src={'/blog-2-8.png'} alt="" width={600} height={100} className="mx-auto mt-4" />
                        <figcaption className="text-center text-xs italic mt-2">Những kỹ năng mới sẽ hỗ trợ trẻ nhiều trong cuộc sống từ đó trẻ sẽ dạn dĩ hơn trong các hoạt động hằng ngày</figcaption>
                        <div className="mt-2 text-xs tracking-wide">Trẻ cũng gặt hái được phần thưởng là sự công nhận từ những người khác đối với thành tích của mình. Quan trọng nhất, trẻ sẽ phát hiện ra rằng mình có một số quyền kiểm soát cuộc sống: Nếu con cố gắng làm điều gì đó, cùng với sự kiên trì, thì cuối cùng con sẽ thành công. Đây cũng là một yếu tố quan trọng để xác định hạnh phúc của người trưởng thành.</div>
                        <h4 className="mt-2 font-semibold text-lg">Cho phép trẻ buồn hoặc tức giận</h4>
                        <div className="mt-2 text-xs tracking-wide">Khi con bạn tỏ thái độ buồn chán, chui vào một góc trong bữa tiệc sinh nhật, phản ứng tự nhiên của bạn có thể là nói: &quot;Con phải vui vẻ như mọi người chứ!&quot;. Cũng có một số cha mẹ cảm lo lắng quá mức mỗi khi đứa con bé bỏng của họ bị từ chối, không được mời đến bữa tiệc sinh nhật bạn bè, hoặc mỗi khi bé khóc vì không đạt được như ý muốn.</div>
                        <div className="mt-2 text-xs tracking-wide">Trẻ em cần biết rằng đôi khi buồn bã cũng không sao, đó chỉ là một phần của cuộc sống. Nếu bạn cố gắng kìm nén tất cả mọi điều không vui, bé có thể hiểu rằng cảm giác buồn bã là sai trái. Hãy để con bạn trải nghiệm mọi cảm giác chân thực, bao gồm cả nỗi buồn.</div>
                        <Image src={'/blog-2-9.png'} alt="" width={600} height={100} className="mx-auto mt-4" />
                        <figcaption className="text-center text-xs italic mt-2">Hãy cho phép trẻ bộc lộ cảm xúc của mình để trẻ không bị bức bối bởi những cảm xúc tiêu cực</figcaption>
                        <div className="mt-2 text-xs tracking-wide">Thay vì dồn nén vào trong, hãy khuyến khích con bạn thể hiện cảm xúc của mình bằng lời nói. Đừng cố gắng giải quyết các vấn đề của con, thay vào đó là hãy lắng nghe và giúp con hướng giải quyết.</div>
                        <div className="mt-2 text-xs tracking-wide">Ví dụ, hãy cho phép bé nói: “Mẹ, con rất giận mẹ” hoặc “Con rất buồn vì hôm nay không được đi chơi”. Khi đó, bố mẹ có thể trả lời rằng: &quot;Bố mẹ xin lỗi vì làm con buồn bực&quot; hoặc &quot;Bố mẹ cũng rất tiếc, cũng buồn&quot;, và tiếp tục trò chuyện với con.</div>
                        <h4 className="mt-2 font-semibold text-lg">Lắng nghe con</h4>
                        <div className="mt-2 text-xs tracking-wide">Lời khuyên tốt nhất và đơn giản nhất để biết con bạn có hạnh phúc hay không là: Lắng nghe. Bạn có thể hỏi trực tiếp rằng con có hạnh phúc không và xem phản ứng của con, hoặc chí ít thì đây cũng là một cách thể hiện sự quan tâm.</div>
                        <div className="mt-2 text-xs tracking-wide">Giao tiếp cởi mở là điều cần thiết để hiểu được tâm trạng của con bạn. Ví dụ, hãy nói với con: “Con có vẻ buồn. Có điều gì muốn nói với mẹ không? Có điều gì làm con phiền lòng?” Sau đó, hãy để trẻ kể chuyện cho bạn nghe. Nếu bé từ chối chia sẻ, hãy thử lại vào ngày hôm sau.</div>
                        <div className="mt-2 text-xs tracking-wide">Nếu bạn lo lắng rằng con đang phải đối mặt với một vấn đề nào đó, hãy thử nói chuyện với cô giáo, người chăm sóc thường xuyên và các phụ huynh khác để xem có thông tin gì hữu ích không.</div>
                        <Image src={'/blog-2-10.png'} alt="" width={600} height={100} className="mx-auto mt-4" />
                        <figcaption className="text-center text-xs italic mt-2">Ba mẹ hãy là người bạn đồng hành để chia sẻ những khó khăn của bé</figcaption>
                        <div className="mt-2 text-xs tracking-wide">Hầu hết các trường hợp trẻ không vui hoặc khó chịu là do môi trường sống căng thẳng: đánh nhau với bạn bè, cãi nhau với anh chị em hoặc gia đình bất hòa. Nhưng đôi khi nguồn gốc của sự bất mãn còn nghiêm trọng hơn.</div>
                        <div className="mt-2 text-xs tracking-wide">Nếu bạn thấy các dấu hiệu không vui cứ đeo bám con quá mức - như bé miễn cưỡng đến trường mỗi buổi sáng, lo lắng mất đi bố mẹ, giả vờ bị bệnh, luôn cảm thấy buồn bã, khó ngủ hoặc khó ăn - hãy nói chuyện với bác sĩ hoặc tham khảo ý kiến ​​chuyên gia sức khỏe tâm thần chuyên về trẻ em. Nhìn chung thì trầm cảm ở trẻ mẫu giáo là không phổ biến.</div>
                        <h4 className="mt-2 font-semibold text-lg">Dạy trẻ biết quan tâm và chia sẻ</h4>
                        <div className="mt-2 text-xs tracking-wide">Nghiên cứu cho thấy những người tìm thấy ý nghĩa trong cuộc sống sẽ ít cảm thấy chán nản hơn. Và cả trẻ nhỏ cũng vậy. Ví dụ, khi giúp đỡ mẹ những công việc nhà đơn giản, như lấy quần áo ra khỏi máy sấy, sẽ khiến con bạn cảm thấy vui vì có đóng góp.</div>
                        <div className="mt-2 text-xs tracking-wide">Một số gia đình có thói quen từ thiện và giúp đỡ người khác cũng nuôi con đúng cách. Ví dụ, sau trận lũ lụt, bạn có thể cùng con soạn đồ dùng học tập và balô để quyên góp cho những đứa trẻ khác.</div>
                        <h4 className="mt-2 font-semibold text-lg">Đừng coi con bạn mặc nhiên là một đứa trẻ nhút nhát. </h4>
                        <div className="mt-2 text-xs tracking-wide">Thay vì thế, hãy thấu hiểu cảm giác của con và chỉ cho con cách vượt qua nỗi sợ hãi của bản thân. Ví dụ như: “Đôi khi con cần thời gian để trở nên thoải mái trong những hoàn cảnh mới. Con có nhớ bữa tiệc mình tham gia tuần trước không? Ban đầu con nắm tay mẹ suốt, nhưng đến cuối cùng con đã chơi đùa rất vui vẻ với các bạn đó thôi.”</div>
                        <h4 className="mt-2 font-semibold text-lg">Dạy cho con những cách thức hiệu quả để đối phó với sự sợ hãi. </h4>
                        <div className="mt-2 text-xs tracking-wide">Thuyết phục con hiểu rằng sự nhút nhát là điều bình thường với hầu hết mọi người, và đến cuối cùng con vẫn sẽ ổn thôi. Nhắc nhở con đừng chỉ tập trung vào bản thân mình, mà hãy để ý đến những người khác nữa. Chỉ cho con cách quan tâm đến mọi người, đặt câu hỏi cho những người khác, và lắng nghe câu trả lời từ họ.</div>
                        <h4 className="mt-2 font-semibold text-lg">Dạy con rằng một người bạn tốt là vô cùng quý giá. </h4>
                        <div className="mt-2 text-xs tracking-wide">Một số phụ huynh lo lắng rằng con họ không phù hợp với cuộc sống của những bữa tiệc. Nhưng điều quan trọng nhất là con bạn cảm thấy được sự kết nối, như là một người bạn mà con có thể chuyện trò, hoặc một người mà con có thể chơi cùng vào mỗi giờ giải lao. Không cần con phải có quá nhiều bạn, chỉ một số người bạn thật sự tốt là đủ.</div>
                        <Image src={'/blog-2-11.png'} alt="" width={600} height={100} className="mx-auto mt-4" />
                        <figcaption className="text-center text-xs italic mt-2">Hãy dạy cho bé cách kết nối với các bạn để bé có thể giao tiếp và trò chuyện với bạn nhiều hơn</figcaption>
                        <h4 className="mt-2 font-semibold text-lg">Đừng khiến con bạn mắc phải chứng lo lắng xã hội bằng việc dạy con phải đề phòng những người lạ. </h4>
                        <div className="mt-2 text-xs tracking-wide">Ngược lại, hãy cho con biết rằng con luôn có bố mẹ, hoặc thầy cô giáo ở bên cạnh, vì thế con sẽ không cần phải sợ những người lạ nữa. Một khi con đã đủ lớn để có thể ra đường một mình, hãy trao đổi với con cách để tự bảo vệ bản thân mình.</div>
                        <h4 className="mt-2 font-semibold text-lg">Hãy xem xét đến việc có thể bé đang có những nỗi sợ ở bên trong cần được thể hiện ra ngoài. </h4>
                        <div className="mt-2 text-xs tracking-wide">Khi trẻ trải nghiệm một điều gì đó đáng sợ và không cảm thấy an toàn, ban đầu những cảm xúc này thường bị bé tự dồn nén lại. Tuy nhiên về mặt tự nhiên cơ thể của con người lại luôn có thể cảm nhận được những sự sợ hãi này và khiến cho chúng luôn trực chờ được thoát ra ngoài, chính vì thế lúc nào bé cũng cảm thấy hồi hộp. Nếu như con bạn gặp phải tình trạng này, hãy cho bé cơ hội để chơi những trò chơi có tính kích thích một chút, như là chơi tàu lượn trên không, tất nhiên là phải dưới sự bảo vệ của bạn. Và khi bé đã cảm thấy đủ an toàn để bộc lộ sự sợ hãi của mình ra thành nước mắt, hãy đón nhận chúng. Điều này về lâu dài sẽ giúp bé có thể đối phó một cách tự nhiên với sự nhút nhát của mình và trở nên bạo dạn, linh hoạt hơn.</div>
                        <div className="mt-2 text-xs tracking-wide"><strong>Đồng hành cùng con trong việc xóa bỏ đi sự nhút nhát, giúp con tự tin hơn</strong> là việc mà các bậc cha mẹ cần phải làm. Nhưng không phải người cha người mẹ nào cũng thành công, vì mỗi trẻ có một tính cách khác nhau sẽ có những cách phản ứng khác nhau trước sự giúp đỡ của bố mẹ. Vậy nên việc cần làm của cha mẹ luôn là sự kiên nhẫn. Chúc các bạn thành công!</div>
                        <div className="mt-2 text-xs tracking-wide">Xem thêm các bài viết sau:</div>
                        <ul className="text-xs leading-7 list-disc list-inside tracking-wide mt-2 mb-5">
                            <li><Link className="hover:text-mainGreen transition-all duration-150" href={'https://hipencilstore.com/blogs/choi-cung-be/do-choi-phu-hop-cho-tre-mac-chung-tu-ky'}>Trẻ Tự Kỷ Chơi Gì Để Hoạt Bát Hơn? Top Trò Chơi Dành Cho Bé Tự Kỷ</Link></li>
                            <li><Link className="hover:text-mainGreen transition-all duration-150" href={'https://hipencilstore.com/blogs/choi-cung-be/ba-me-can-biet-co-nen-mua-nhieu-do-choi-cho-tre'}>Ba mẹ cần biết: Có nên mua nhiều đồ chơi cho trẻ?</Link></li>
                            <li><Link className="hover:text-mainGreen transition-all duration-150" href={'https://hipencilstore.com/blogs/bi-quyet-cho-me/co-nen-day-song-ngu-cho-con-tu-nho'}>Bố mẹ có nên cho con học song ngữ cho con từ nhỏ?</Link></li>
                        </ul>
                        <CommentBox />
                    </div>
                </div>
            </div>
        </div>
    )
}

export default Blog2;